 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'majestic ring system');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'Das geschah zu Beginn dieses Monats');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'Solche Mammatus-Wolkenkönnenbesondersdramatisch erscheinen');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'with old stars and lacking gas and dust');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'Doch es sieht so aus, als würden sie auf diesem gruseligen Bild eines exzentrischen');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'die helle Struktur über der Bildmitte, beherbergt mehrere dieser massereichen Sterne und hat');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'Light from the quasar is pulled around');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', '25 light-years across, blown bywinds from its central');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'Pictured above is a unique time-lapse image of the unprecedented double transit');
 SELECT id FROM wiki WHERE to_tsvector('wiki_multi', body) @@ plainto_tsquery('wiki_multi', 'At that time, Cassini snapped several images during an engineering test');
