 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'majestic ring system');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'Das geschah zu Beginn dieses Monats');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'Solche Mammatus-Wolkenkönnenbesondersdramatisch erscheinen');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'with old stars and lacking gas and dust');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'Doch es sieht so aus, als würden sie auf diesem gruseligen Bild eines exzentrischen');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'die helle Struktur über der Bildmitte, beherbergt mehrere dieser massereichen Sterne und hat');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'Light from the quasar is pulled around');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', '25 light-years across, blown bywinds from its central');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'Pictured above is a unique time-lapse image of the unprecedented double transit');
 SELECT id FROM apod WHERE to_tsvector('apod_en_de', body) @@ plainto_tsquery('apod_en_de', 'At that time, Cassini snapped several images during an engineering test');
